name: Create Akun

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  netlify-signup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Setup ChromeDriver
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: latest

      # Step 5: Install Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 6: Run Netlify SignUp Script
      - name: Run Python Script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}  # Replace with actual secret
        run: |
          python create.py  # Replace 'script.py' with the name of your Python file

      # Step 7: Upload logs (optional)
      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: netlify-signup-logs
          path: ./logs/
