name: Netlify Signup Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  netlify-signup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Chrome and ChromeDriver
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          # Remove existing symbolic link if it exists
          if [ -f /usr/bin/chromedriver ]; then
            sudo rm /usr/bin/chromedriver
          fi
          # Create a new symbolic link
          sudo ln -s /usr/bin/chromium-chromedriver /usr/bin/chromedriver

      # Step 5: Install additional libraries for Selenium and clipboard handling
      - name: Install xclip for pyperclip and dependencies
        run: |
          sudo apt-get install -y xclip
          sudo apt-get install -y libnss3-dev libgconf-2-4

      # Step 6: Prepare Gmail API credentials
      - name: Setup Gmail API credentials
        run: |
          echo "${{ secrets.GMAIL_CREDENTIALS }}" > credentials.json
          echo "${{ secrets.GMAIL_TOKEN }}" > token.json

      # Step 7: Run the Python script
      - name: Run the automation script
        run: |
          python create.py

    env:
      # Add Gmail API credentials and token.json from GitHub Secrets
      GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
      GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
