name: Create Akun

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Memungkinkan workflow dijalankan secara manual

jobs:
  run-netlify-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Versi Python yang Anda butuhkan

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}  # Replace with actual secret
        run: |
          python create.py

      # Step 7: Upload logs (optional)
      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: netlify-signup-logs
          path: ./logs/
