name: Run Akun

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-netlify-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xclip
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install undetected-chromedriver==2.1.1 webdriver-manager  # Tambahkan paket webdriver-manager

      - name: Run Netlify Bot Script
        env:
          DISPLAY: :99
        run: |
          Xvfb :99 &  
          python run.py  

      - name: Upload API output
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: api-results
          path: api.txt
