name: Run Selenium Script

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can change this to your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install undetected-chromedriver  # Install undetected-chromedriver

    - name: Run Selenium script
      run: python run.py  # Change this to the name of your script
