name: Run Script

on:
  push:
    branches:
      - main  # Change to your main branch name
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your Python version here

      - name: Install xclip
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xclip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Make sure to have a requirements.txt with all your dependencies

      - name: Run Netlify Bot Script
        env:
          DISPLAY: :99  # Untuk headless chrome jika diperlukan
        run: |
          Xvfb :99 &  # Menjalankan virtual display di background
          python run.py  # Ganti dengan nama file skrip Python Anda

      - name: Upload API Output
        uses: actions/upload-artifact@v3
        with:
          name: api-output
          path: api.txt  # Path to the file containing the copied API
