name: Run Python Scripts

on:
  push:
    branches:
      - main  # Atur ini sesuai dengan cabang yang ingin Anda gunakan
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual

jobs:
  run-scripts:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ganti dengan versi Python yang Anda butuhkan

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run instance 1
        run: |
          echo "Running instance 1"
          python create2.py && python run2.py

      - name: Run instance 2
        run: |
          echo "Running instance 2"
          python create2.py && python run2.py

      - name: Run instance 3
        run: |
          echo "Running instance 3"
          python create2.py && python run2.py

      - name: Run instance 4
        run: |
          echo "Running instance 4"
          python create2.py && python run2.py

      - name: Run instance 5
        run: |
          echo "Running instance 5"
          python create2.py && python run2.py
