name: Run Selenium Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.14'  # You can change this to your desired Python version

    - name: Set up ChromeDriver
      run: |
        sudo apt-get install -y libnss3
        sudo apt-get install -y libxss1
        wget -q https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb xclip  # Menambahkan instalasi xclip untuk clipboard
        pip install -r requirements.txt
        python -m pip install --upgrade pip
        pip install undetected-chromedriver  # Install undetected-chromedriver

    - name: Run Selenium script
      run: python run.py  # Change this to the name of your script
