name: Run Python Scripts

on:
  schedule:
    - cron: "*/80 * * * *"  # Menjalankan setiap 1 jam 30 menit
  push:
    branches:
      - main  # Atur ini sesuai dengan cabang yang ingin Anda gunakan
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual

jobs:
  run-scripts:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ganti dengan versi Python yang Anda butuhkan

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: CREATE AKUN
        run: |
          python create2.py

      - name: RUNNNNN
        run: |
          python run.py
