name: Run Selenium Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Sesuaikan versi Python jika perlu

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install webdriver-manager undetected-chromedriver pyperclip

    - name: Install Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Run Selenium script
      env:
        DISPLAY: :99
      run: |
        Xvfb :99 -screen 0 1024x768x16 &
        python run.py

    - name: Archive results
      if: always()
      uses: actions/upload-artifact@v3  # Menggunakan versi v3 yang terbaru
      with:
        name: api-output
        path: api.txt
