name: Run Akun

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Memungkinkan workflow dijalankan secara manual

jobs:
  run-netlify-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Versi Python yang Anda butuhkan

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xclip wget unzip  # Menambahkan instalasi xclip untuk clipboard
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Latest Stable Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version  # Memverifikasi versi Chrome yang terinstal

      - name: Install ChromeDriver using WebDriver Manager
        run: |
          python -m pip install webdriver-manager  # Menginstal webdriver-manager
          python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"  # Mengunduh ChromeDriver sesuai dengan Chrome

      - name: Run Netlify Bot Script
        env:
          DISPLAY: :99  # Untuk headless chrome jika diperlukan
        run: |
          Xvfb :99 &  # Menjalankan virtual display di background
          python run.py  # Ganti dengan nama file skrip Python Anda

      - name: Upload API output
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: api-results
          path: api.txt  # Mengunggah hasil API ke GitHub sebagai artifact
