name: Run Python Scripts

on:
  push:
    branches:
      - main  # Atur ini sesuai dengan cabang yang ingin Anda gunakan
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual

jobs:
  run-scripts:
    runs-on: windows-latest

    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5]  # Membuat 5 instance

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ganti dengan versi Python yang Anda butuhkan

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run create.py and run.py
        run: |
          python create2.py && python run2.py
